// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: tune_bar

#include "../ui.h"

lv_obj_t * ui_Screen_Info = NULL;
lv_obj_t * ui_Info_Label_BattStatus = NULL;
lv_obj_t * ui_Info_Panel_Clock = NULL;
lv_obj_t * ui_Info_Image_hour0 = NULL;
lv_obj_t * ui_Info_Image_hour1 = NULL;
lv_obj_t * ui_Info_Image_colon0 = NULL;
lv_obj_t * ui_Info_Image_minute0 = NULL;
lv_obj_t * ui_Info_Image_minute1 = NULL;
lv_obj_t * ui_Info_Image_colon1 = NULL;
lv_obj_t * ui_Info_Image_second0 = NULL;
lv_obj_t * ui_Info_Image_second1 = NULL;
lv_obj_t * ui_Info_Label_DateNixie = NULL;
lv_obj_t * ui_Info_Panel_Weather = NULL;
lv_obj_t * ui_Info_Image_Home = NULL;
lv_obj_t * ui_Info_Image_Turbine = NULL;
lv_obj_t * ui_Info_Image_Propeller = NULL;
lv_obj_t * ui_Info_Image_WeatherIcon = NULL;
lv_obj_t * ui_Info_Image_cat = NULL;
lv_obj_t * ui_Info_Image_dog = NULL;
lv_obj_t * ui_Info_Container_WeatherDetail = NULL;
lv_obj_t * ui_Info_Label_Detail = NULL;
lv_obj_t * ui_Info_Label_Temp = NULL;
lv_obj_t * ui_Info_Label_LastUpdated = NULL;
lv_obj_t * ui_Info_Label_DateTime = NULL;
lv_obj_t * ui_Info_Label_Label23 = NULL;
lv_obj_t * ui_Info_Panel_AQI = NULL;
lv_obj_t * ui_Info_Label_AQIvalue = NULL;
lv_obj_t * ui_Info_Label_Label24 = NULL;
lv_obj_t * ui_Info_Label_AQIdominant = NULL;
lv_obj_t * ui_Info_Label_AQIrate = NULL;
lv_obj_t * ui_Info_Label_AQIlocation = NULL;
lv_obj_t * ui_Info_Image_AQIimage = NULL;
lv_obj_t * ui_Info_Button_returnMenu = NULL;
lv_obj_t * ui_Info_Label_Label21 = NULL;
lv_obj_t * ui_Info_Button_infoPanelLeft = NULL;
lv_obj_t * ui_Info_Label_Label19 = NULL;
lv_obj_t * ui_Info_Button_infoPanelRight = NULL;
lv_obj_t * ui_Info_Label_Label22 = NULL;
lv_obj_t * ui_Info_Panel_blindPanel = NULL;
// event funtions
void ui_event_Screen_Info(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen_MainMenu, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Screen_MainMenu_screen_init);
        stopWeatherAnimation(e);
        exit_clock_breathing();
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        changeInfoPanelNext(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        changeInfoPanelPrev(e);
    }
    if(event_code == LV_EVENT_PRESSED) {
        showArrow(e);
    }
}

void ui_event_Info_Panel_Clock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        showArrow(e);
    }
}

void ui_event_Info_Panel_Weather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        showArrow(e);
    }
}

void ui_event_Info_Label_LastUpdated(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen_MainMenu, LV_SCR_LOAD_ANIM_OUT_TOP, 500, 0, &ui_Screen_MainMenu_screen_init);
    }
}

void ui_event_Info_Label_DateTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen_MainMenu, LV_SCR_LOAD_ANIM_OUT_TOP, 500, 0, &ui_Screen_MainMenu_screen_init);
    }
}

void ui_event_Info_Panel_AQI(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        showArrow(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        updateAQIwidget(e);
    }
}

void ui_event_Info_Button_returnMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_MainMenu, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Screen_MainMenu_screen_init);
        stopWeatherAnimation(e);
        exit_clock_breathing();
    }
}

void ui_event_Info_Button_infoPanelLeft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        changeInfoPanelPrev(e);
    }
}

void ui_event_Info_Button_infoPanelRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        changeInfoPanelNext(e);
    }
}

void ui_event_Info_Panel_blindPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        turnonScreen(e);
    }
}

// build funtions

void ui_Screen_Info_screen_init(void)
{
    ui_Screen_Info = lv_obj_create(NULL);
    lv_obj_add_flag(ui_Screen_Info, LV_OBJ_FLAG_SCROLL_WITH_ARROW | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Screen_Info, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Screen_Info, LV_DIR_HOR);
    lv_obj_set_style_text_font(ui_Screen_Info, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Panel_Clock = lv_obj_create(ui_Screen_Info);
    lv_obj_set_width(ui_Info_Panel_Clock, 640);
    lv_obj_set_height(ui_Info_Panel_Clock, 172);
    lv_obj_set_align(ui_Info_Panel_Clock, LV_ALIGN_LEFT_MID);
    // Clock is default visible     /// Flags
    lv_obj_clear_flag(ui_Info_Panel_Clock,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Info_Panel_Clock, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_Info_Panel_Clock, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_radius(ui_Info_Panel_Clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Info_Panel_Clock, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Panel_Clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Info_Panel_Clock, lv_color_hex(0x6C6969), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Info_Panel_Clock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Image_hour0 = lv_img_create(ui_Info_Panel_Clock);
    lv_img_set_src(ui_Info_Image_hour0, &ui_img_numbers_0_png);
    lv_obj_set_width(ui_Info_Image_hour0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Image_hour0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Image_hour0, -224);
    lv_obj_set_y(ui_Info_Image_hour0, 25);
    lv_obj_set_align(ui_Info_Image_hour0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Info_Image_hour0, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Info_Image_hour0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Info_Image_hour1 = lv_img_create(ui_Info_Panel_Clock);
    lv_img_set_src(ui_Info_Image_hour1, &ui_img_numbers_0_png);
    lv_obj_set_width(ui_Info_Image_hour1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Image_hour1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Image_hour1, -160);
    lv_obj_set_y(ui_Info_Image_hour1, 25);
    lv_obj_set_align(ui_Info_Image_hour1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Info_Image_hour1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Info_Image_hour1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Info_Image_colon0 = lv_img_create(ui_Info_Panel_Clock);
    lv_img_set_src(ui_Info_Image_colon0, &ui_img_numbers_colon_png);
    lv_obj_set_width(ui_Info_Image_colon0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Image_colon0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Image_colon0, -96);
    lv_obj_set_y(ui_Info_Image_colon0, 25);
    lv_obj_set_align(ui_Info_Image_colon0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Info_Image_colon0, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Info_Image_colon0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Info_Image_minute0 = lv_img_create(ui_Info_Panel_Clock);
    lv_img_set_src(ui_Info_Image_minute0, &ui_img_numbers_0_png);
    lv_obj_set_width(ui_Info_Image_minute0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Image_minute0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Image_minute0, -32);
    lv_obj_set_y(ui_Info_Image_minute0, 25);
    lv_obj_set_align(ui_Info_Image_minute0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Info_Image_minute0, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Info_Image_minute0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Info_Image_minute1 = lv_img_create(ui_Info_Panel_Clock);
    lv_img_set_src(ui_Info_Image_minute1, &ui_img_numbers_0_png);
    lv_obj_set_width(ui_Info_Image_minute1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Image_minute1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Image_minute1, 32);
    lv_obj_set_y(ui_Info_Image_minute1, 25);
    lv_obj_set_align(ui_Info_Image_minute1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Info_Image_minute1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Info_Image_minute1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Info_Image_colon1 = lv_img_create(ui_Info_Panel_Clock);
    lv_img_set_src(ui_Info_Image_colon1, &ui_img_numbers_colon_png);
    lv_obj_set_width(ui_Info_Image_colon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Image_colon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Image_colon1, 96);
    lv_obj_set_y(ui_Info_Image_colon1, 25);
    lv_obj_set_align(ui_Info_Image_colon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Info_Image_colon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Info_Image_colon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Info_Image_second0 = lv_img_create(ui_Info_Panel_Clock);
    lv_img_set_src(ui_Info_Image_second0, &ui_img_numbers_0_png);
    lv_obj_set_width(ui_Info_Image_second0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Image_second0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Image_second0, 160);
    lv_obj_set_y(ui_Info_Image_second0, 25);
    lv_obj_set_align(ui_Info_Image_second0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Info_Image_second0, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Info_Image_second0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Info_Image_second1 = lv_img_create(ui_Info_Panel_Clock);
    lv_img_set_src(ui_Info_Image_second1, &ui_img_numbers_0_png);
    lv_obj_set_width(ui_Info_Image_second1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Image_second1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Image_second1, 224);
    lv_obj_set_y(ui_Info_Image_second1, 25);
    lv_obj_set_align(ui_Info_Image_second1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Info_Image_second1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Info_Image_second1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Info_Label_DateNixie = lv_label_create(ui_Info_Panel_Clock);
    lv_obj_set_width(ui_Info_Label_DateNixie, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Label_DateNixie, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Label_DateNixie, 0);
    lv_obj_set_y(ui_Info_Label_DateNixie, -15);
    lv_obj_set_align(ui_Info_Label_DateNixie, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Info_Label_DateNixie, "Sat, Nov 23, 1974");
    lv_obj_set_style_text_color(ui_Info_Label_DateNixie, lv_color_hex(0xDD9C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info_Label_DateNixie, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Info_Label_DateNixie, &ui_font_NixieOne48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Panel_Weather = lv_obj_create(ui_Screen_Info);
    lv_obj_set_width(ui_Info_Panel_Weather, lv_pct(100));
    lv_obj_set_height(ui_Info_Panel_Weather, lv_pct(100));
    lv_obj_set_align(ui_Info_Panel_Weather, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Info_Panel_Weather, LV_OBJ_FLAG_HIDDEN);     /// Default hidden (second panel)
    lv_obj_clear_flag(ui_Info_Panel_Weather,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Info_Panel_Weather, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_Info_Panel_Weather, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_radius(ui_Info_Panel_Weather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Info_Panel_Weather, lv_color_hex(0x41B3FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Panel_Weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Info_Panel_Weather, lv_color_hex(0x228322), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Info_Panel_Weather, 170, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Info_Panel_Weather, 190, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Info_Panel_Weather, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Info_Panel_Weather, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Info_Panel_Weather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Image_Home = lv_img_create(ui_Info_Panel_Weather);
    lv_img_set_src(ui_Info_Image_Home, &ui_img_weather_home_sunny_png);
    lv_obj_set_width(ui_Info_Image_Home, 96);
    lv_obj_set_height(ui_Info_Image_Home, 96);
    lv_obj_set_x(ui_Info_Image_Home, 242);
    lv_obj_set_y(ui_Info_Image_Home, 17);
    lv_obj_set_align(ui_Info_Image_Home, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Info_Image_Home, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Info_Image_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Info_Image_Turbine = lv_img_create(ui_Info_Panel_Weather);
    lv_img_set_src(ui_Info_Image_Turbine, &ui_img_weather_stack_png);
    lv_obj_set_width(ui_Info_Image_Turbine, LV_SIZE_CONTENT);   /// 96
    lv_obj_set_height(ui_Info_Image_Turbine, LV_SIZE_CONTENT);    /// 96
    lv_obj_set_x(ui_Info_Image_Turbine, 145);
    lv_obj_set_y(ui_Info_Image_Turbine, 19);
    lv_obj_set_align(ui_Info_Image_Turbine, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Info_Image_Turbine, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Info_Image_Turbine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Info_Image_Propeller = lv_img_create(ui_Info_Panel_Weather);
    lv_img_set_src(ui_Info_Image_Propeller, &ui_img_weather_propeller_png);
    lv_obj_set_width(ui_Info_Image_Propeller, LV_SIZE_CONTENT);   /// 96
    lv_obj_set_height(ui_Info_Image_Propeller, LV_SIZE_CONTENT);    /// 96
    lv_obj_set_x(ui_Info_Image_Propeller, 122);
    lv_obj_set_y(ui_Info_Image_Propeller, -9);
    lv_obj_set_align(ui_Info_Image_Propeller, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Info_Image_Propeller, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Info_Image_Propeller, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Info_Image_WeatherIcon = lv_img_create(ui_Info_Panel_Weather);
    lv_obj_set_width(ui_Info_Image_WeatherIcon, 96);
    lv_obj_set_height(ui_Info_Image_WeatherIcon, 96);
    lv_obj_set_x(ui_Info_Image_WeatherIcon, 28);
    lv_obj_set_y(ui_Info_Image_WeatherIcon, -18);
    lv_obj_set_align(ui_Info_Image_WeatherIcon, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Info_Image_WeatherIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Info_Image_WeatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Info_Image_cat = lv_img_create(ui_Info_Panel_Weather);
    lv_img_set_src(ui_Info_Image_cat, &ui_img_custom_cat_right1_png);
    lv_obj_set_width(ui_Info_Image_cat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Image_cat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Image_cat, 221);
    lv_obj_set_y(ui_Info_Image_cat, -20);
    lv_obj_set_align(ui_Info_Image_cat, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Info_Image_cat, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Info_Image_cat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Info_Image_dog = lv_img_create(ui_Info_Panel_Weather);
    lv_img_set_src(ui_Info_Image_dog, &ui_img_custom_dog_left1_png);
    lv_obj_set_width(ui_Info_Image_dog, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Image_dog, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Image_dog, 179);
    lv_obj_set_y(ui_Info_Image_dog, -15);
    lv_obj_set_align(ui_Info_Image_dog, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Info_Image_dog, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Info_Image_dog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Info_Container_WeatherDetail = lv_obj_create(ui_Info_Panel_Weather);
    lv_obj_remove_style_all(ui_Info_Container_WeatherDetail);
    lv_obj_set_height(ui_Info_Container_WeatherDetail, 130);
    lv_obj_set_width(ui_Info_Container_WeatherDetail, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Info_Container_WeatherDetail, -18);
    lv_obj_set_y(ui_Info_Container_WeatherDetail, 0);
    lv_obj_set_align(ui_Info_Container_WeatherDetail, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Info_Container_WeatherDetail, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Info_Container_WeatherDetail, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info_Container_WeatherDetail, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Label_Detail = lv_label_create(ui_Info_Container_WeatherDetail);
    lv_obj_set_width(ui_Info_Label_Detail, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Label_Detail, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Label_Detail, 18);
    lv_obj_set_y(ui_Info_Label_Detail, 3);
    lv_label_set_text(ui_Info_Label_Detail, "Weather conditions:");
    lv_obj_set_style_text_align(ui_Info_Label_Detail, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Info_Label_Detail, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Label_Temp = lv_label_create(ui_Info_Container_WeatherDetail);
    lv_obj_set_width(ui_Info_Label_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Label_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Label_Temp, 18);
    lv_obj_set_y(ui_Info_Label_Temp, 3);
    lv_obj_set_align(ui_Info_Label_Temp, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Info_Label_Temp, "0.0°c");
    lv_obj_set_style_text_align(ui_Info_Label_Temp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Info_Label_Temp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Label_LastUpdated = lv_label_create(ui_Info_Panel_Weather);
    lv_obj_set_width(ui_Info_Label_LastUpdated, 400);
    lv_obj_set_height(ui_Info_Label_LastUpdated, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Label_LastUpdated, -18);
    lv_obj_set_y(ui_Info_Label_LastUpdated, 18);
    lv_obj_set_align(ui_Info_Label_LastUpdated, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_long_mode(ui_Info_Label_LastUpdated, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Info_Label_LastUpdated, "Last updated:");
    lv_obj_set_style_text_color(ui_Info_Label_LastUpdated, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info_Label_LastUpdated, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Info_Label_LastUpdated, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Info_Label_LastUpdated, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Info_Label_LastUpdated, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Label_LastUpdated, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Label_DateTime = lv_label_create(ui_Info_Panel_Weather);
    lv_obj_set_width(ui_Info_Label_DateTime, 400);
    lv_obj_set_height(ui_Info_Label_DateTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Label_DateTime, -18);
    lv_obj_set_y(ui_Info_Label_DateTime, -18);
    lv_label_set_long_mode(ui_Info_Label_DateTime, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Info_Label_DateTime, "Sat, Nov 23, 1974 - 12:00:00");
    lv_obj_set_scrollbar_mode(ui_Info_Label_DateTime, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_Info_Label_DateTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info_Label_DateTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Info_Label_DateTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Info_Label_DateTime, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Info_Label_DateTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Label_DateTime, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Label_Label23 = lv_label_create(ui_Info_Panel_Weather);
    lv_obj_set_width(ui_Info_Label_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Label_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Label_Label23, 2);
    lv_obj_set_y(ui_Info_Label_Label23, 60);
    lv_obj_set_align(ui_Info_Label_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Info_Label_Label23, "Powered by WeatherAPI.com");
    lv_obj_set_style_text_color(ui_Info_Label_Label23, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info_Label_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Info_Label_Label23, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Panel_AQI = lv_obj_create(ui_Info_Panel_Weather);
    lv_obj_set_width(ui_Info_Panel_AQI, 240);
    lv_obj_set_height(ui_Info_Panel_AQI, 172);
    lv_obj_set_x(ui_Info_Panel_AQI, 18);
    lv_obj_set_y(ui_Info_Panel_AQI, 0);
    lv_obj_set_align(ui_Info_Panel_AQI, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Info_Panel_AQI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Info_Panel_AQI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Info_Panel_AQI, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Panel_AQI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Info_Panel_AQI, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Info_Panel_AQI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Info_Panel_AQI, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Info_Panel_AQI, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Label_AQIvalue = lv_label_create(ui_Info_Panel_AQI);
    lv_obj_set_width(ui_Info_Label_AQIvalue, 100);
    lv_obj_set_height(ui_Info_Label_AQIvalue, 60);
    lv_obj_set_x(ui_Info_Label_AQIvalue, 0);
    lv_obj_set_y(ui_Info_Label_AQIvalue, -16);
    lv_obj_set_align(ui_Info_Label_AQIvalue, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_Info_Label_AQIvalue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Info_Label_AQIvalue, "0");
    lv_obj_set_style_text_color(ui_Info_Label_AQIvalue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info_Label_AQIvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Info_Label_AQIvalue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Info_Label_AQIvalue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Info_Label_AQIvalue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Info_Label_AQIvalue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Label_AQIvalue, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Label_Label24 = lv_label_create(ui_Info_Label_AQIvalue);
    lv_obj_set_width(ui_Info_Label_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Label_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Info_Label_Label24, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Info_Label_Label24, "US AQI");
    lv_obj_set_style_text_color(ui_Info_Label_Label24, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info_Label_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Info_Label_Label24, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Label_AQIdominant = lv_label_create(ui_Info_Panel_AQI);
    lv_obj_set_width(ui_Info_Label_AQIdominant, lv_pct(100));
    lv_obj_set_height(ui_Info_Label_AQIdominant, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Label_AQIdominant, 0);
    lv_obj_set_y(ui_Info_Label_AQIdominant, 13);
    lv_obj_set_align(ui_Info_Label_AQIdominant, LV_ALIGN_BOTTOM_MID);
    lv_label_set_long_mode(ui_Info_Label_AQIdominant, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Info_Label_AQIdominant, "PM2.5 | 0.0 ug/m3");
    lv_obj_set_style_text_color(ui_Info_Label_AQIdominant, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info_Label_AQIdominant, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Info_Label_AQIdominant, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Info_Label_AQIdominant, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Info_Label_AQIdominant, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Info_Label_AQIdominant, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Label_AQIdominant, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Label_AQIrate = lv_label_create(ui_Info_Panel_AQI);
    lv_obj_set_width(ui_Info_Label_AQIrate, lv_pct(100));
    lv_obj_set_height(ui_Info_Label_AQIrate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Label_AQIrate, 0);
    lv_obj_set_y(ui_Info_Label_AQIrate, -22);
    lv_obj_set_align(ui_Info_Label_AQIrate, LV_ALIGN_BOTTOM_MID);
    lv_label_set_long_mode(ui_Info_Label_AQIrate, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Info_Label_AQIrate, "Touch this widget to update weather condition");
    lv_obj_set_style_text_color(ui_Info_Label_AQIrate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info_Label_AQIrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Info_Label_AQIrate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Info_Label_AQIrate, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Info_Label_AQIrate, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Info_Label_AQIrate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Label_AQIrate, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Label_AQIlocation = lv_label_create(ui_Info_Panel_AQI);
    lv_obj_set_width(ui_Info_Label_AQIlocation, lv_pct(100));
    lv_obj_set_height(ui_Info_Label_AQIlocation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Label_AQIlocation, 0);
    lv_obj_set_y(ui_Info_Label_AQIlocation, -14);
    lv_obj_set_align(ui_Info_Label_AQIlocation, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_Info_Label_AQIlocation, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Info_Label_AQIlocation, "Air Pollution");
    lv_obj_set_style_text_align(ui_Info_Label_AQIlocation, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Info_Label_AQIlocation, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Info_Label_AQIlocation, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Info_Label_AQIlocation, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Label_AQIlocation, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Image_AQIimage = lv_img_create(ui_Info_Panel_AQI);
    lv_obj_set_width(ui_Info_Image_AQIimage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Image_AQIimage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Info_Image_AQIimage, 2);
    lv_obj_set_y(ui_Info_Image_AQIimage, -17);
    lv_obj_set_align(ui_Info_Image_AQIimage, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Info_Image_AQIimage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Info_Image_AQIimage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Info_Button_returnMenu = lv_btn_create(ui_Screen_Info);
    lv_obj_set_width(ui_Info_Button_returnMenu, 100);
    lv_obj_set_height(ui_Info_Button_returnMenu, 40);
    lv_obj_set_align(ui_Info_Button_returnMenu, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Info_Button_returnMenu, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Info_Button_returnMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Info_Button_returnMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Info_Button_returnMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Button_returnMenu, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Info_Button_returnMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Info_Button_returnMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Label_Label21 = lv_label_create(ui_Info_Button_returnMenu);
    lv_obj_set_width(ui_Info_Label_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Label_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Info_Label_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Info_Label_Label21, "V");
    lv_obj_set_style_text_color(ui_Info_Label_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info_Label_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Info_Label_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Info_Label_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Info_Label_Label21, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Info_Label_Label21, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Button_infoPanelLeft = lv_btn_create(ui_Screen_Info);
    lv_obj_set_width(ui_Info_Button_infoPanelLeft, 40);
    lv_obj_set_height(ui_Info_Button_infoPanelLeft, lv_pct(100));
    lv_obj_set_align(ui_Info_Button_infoPanelLeft, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Info_Button_infoPanelLeft, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Info_Button_infoPanelLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Info_Button_infoPanelLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Info_Button_infoPanelLeft, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Button_infoPanelLeft, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Info_Button_infoPanelLeft, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Info_Button_infoPanelLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Label_Label19 = lv_label_create(ui_Info_Button_infoPanelLeft);
    lv_obj_set_width(ui_Info_Label_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Label_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Info_Label_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Info_Label_Label19, "<");
    lv_obj_set_style_text_color(ui_Info_Label_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info_Label_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Button_infoPanelRight = lv_btn_create(ui_Screen_Info);
    lv_obj_set_width(ui_Info_Button_infoPanelRight, 40);
    lv_obj_set_height(ui_Info_Button_infoPanelRight, lv_pct(100));
    lv_obj_set_align(ui_Info_Button_infoPanelRight, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Info_Button_infoPanelRight, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Info_Button_infoPanelRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Info_Button_infoPanelRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Info_Button_infoPanelRight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Button_infoPanelRight, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Info_Button_infoPanelRight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Info_Button_infoPanelRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Label_Label22 = lv_label_create(ui_Info_Button_infoPanelRight);
    lv_obj_set_width(ui_Info_Label_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Info_Label_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Info_Label_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Info_Label_Label22, ">");
    lv_obj_set_style_text_color(ui_Info_Label_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info_Label_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Panel_blindPanel = lv_obj_create(ui_Screen_Info);
    lv_obj_set_width(ui_Info_Panel_blindPanel, lv_pct(100));
    lv_obj_set_height(ui_Info_Panel_blindPanel, lv_pct(100));
    lv_obj_set_align(ui_Info_Panel_blindPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Info_Panel_blindPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Info_Panel_blindPanel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Info_Panel_blindPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Info_Panel_blindPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Info_Panel_blindPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Panel_blindPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Info_Panel_blindPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Info_Panel_blindPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

        ui_Info_Label_BattStatus = lv_label_create(ui_Info_Panel_Clock);
    lv_obj_set_width(ui_Info_Label_BattStatus, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Info_Label_BattStatus, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_Info_Label_BattStatus, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_x(ui_Info_Label_BattStatus, -10);
    lv_obj_set_y(ui_Info_Label_BattStatus, 8);
    lv_label_set_text(ui_Info_Label_BattStatus, "");
    lv_obj_set_style_text_color(ui_Info_Label_BattStatus, lv_color_hex(0xDD9C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Info_Label_BattStatus, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    alarm_ui_init(ui_Screen_Info);

    lv_obj_add_event_cb(ui_Info_Panel_Clock, ui_event_Info_Panel_Clock, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Info_Label_LastUpdated, ui_event_Info_Label_LastUpdated, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Info_Label_DateTime, ui_event_Info_Label_DateTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Info_Panel_AQI, ui_event_Info_Panel_AQI, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Info_Panel_Weather, ui_event_Info_Panel_Weather, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Info_Button_returnMenu, ui_event_Info_Button_returnMenu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Info_Button_infoPanelLeft, ui_event_Info_Button_infoPanelLeft, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Info_Button_infoPanelRight, ui_event_Info_Button_infoPanelRight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Info_Panel_blindPanel, ui_event_Info_Panel_blindPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Info, ui_event_Screen_Info, LV_EVENT_ALL, NULL);

}

void ui_Screen_Info_screen_destroy(void)
{
    if(ui_Screen_Info) lv_obj_del(ui_Screen_Info);

    // NULL screen variables
    ui_Screen_Info = NULL;
    ui_Info_Panel_Alarm = NULL;
    ui_Info_Panel_Clock = NULL;
    ui_Info_Label_BattStatus = NULL;
    ui_Info_Image_hour0 = NULL;
    ui_Info_Image_hour1 = NULL;
    ui_Info_Image_colon0 = NULL;
    ui_Info_Image_minute0 = NULL;
    ui_Info_Image_minute1 = NULL;
    ui_Info_Image_colon1 = NULL;
    ui_Info_Image_second0 = NULL;
    ui_Info_Image_second1 = NULL;
    ui_Info_Label_DateNixie = NULL;
    ui_Info_Panel_Weather = NULL;
    ui_Info_Image_Home = NULL;
    ui_Info_Image_Turbine = NULL;
    ui_Info_Image_Propeller = NULL;
    ui_Info_Image_WeatherIcon = NULL;
    ui_Info_Image_cat = NULL;
    ui_Info_Image_dog = NULL;
    ui_Info_Container_WeatherDetail = NULL;
    ui_Info_Label_Detail = NULL;
    ui_Info_Label_Temp = NULL;
    ui_Info_Label_LastUpdated = NULL;
    ui_Info_Label_DateTime = NULL;
    ui_Info_Label_Label23 = NULL;
    ui_Info_Panel_AQI = NULL;
    ui_Info_Label_AQIvalue = NULL;
    ui_Info_Label_Label24 = NULL;
    ui_Info_Label_AQIdominant = NULL;
    ui_Info_Label_AQIrate = NULL;
    ui_Info_Label_AQIlocation = NULL;
    ui_Info_Image_AQIimage = NULL;
    ui_Info_Button_returnMenu = NULL;
    ui_Info_Label_Label21 = NULL;
    ui_Info_Button_infoPanelLeft = NULL;
    ui_Info_Label_Label19 = NULL;
    ui_Info_Button_infoPanelRight = NULL;
    ui_Info_Label_Label22 = NULL;
    ui_Info_Panel_blindPanel = NULL;

}
