// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: tune_bar

#include "../ui.h"

lv_obj_t * ui_Screen_Utility = NULL;
lv_obj_t * ui_Utility_Image_TorchButton = NULL;
lv_obj_t * ui_Utility_Image_SystemInfoButton = NULL;
lv_obj_t * ui_Utility_Panel_Torch = NULL;
lv_obj_t * ui_Utility_Label_Label26 = NULL;
lv_obj_t * ui_Utility_Panel_SystemInfo = NULL;
lv_obj_t * ui_Utility_Label_Build = NULL;
lv_obj_t * ui_Utility_Label_Memory = NULL;
lv_obj_t * ui_Utility_Label_Metrics = NULL;
lv_obj_t * ui_Utility_Image_qrcode = NULL;
lv_obj_t * ui_Utility_Button_closeConfig2 = NULL;
lv_obj_t * ui_Utility_Label_Label28 = NULL;
lv_obj_t * ui_Utility_Button_UpdateFirmware = NULL;
lv_obj_t * ui_Utility_Label_Label11 = NULL;
lv_obj_t * ui_Utility_Button_returnMenu = NULL;
lv_obj_t * ui_Utility_Label_Label27 = NULL;
lv_obj_t * ui_Utility_Panel_blindPanel = NULL;
// event funtions
void ui_event_Screen_Utility(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen_MainMenu, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen_MainMenu_screen_init);
    }
    if(event_code == LV_EVENT_PRESSED) {
        showArrow(e);
    }
}

void ui_event_Utility_Image_TorchButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Utility_Panel_Torch, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        torch_ON(e);
        _ui_flag_modify(ui_Utility_Button_returnMenu, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen_MainMenu, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen_MainMenu_screen_init);
    }
}

void ui_event_Utility_Image_SystemInfoButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Utility_Panel_SystemInfo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        showSystemInfo(e);
        _ui_flag_modify(ui_Utility_Button_returnMenu, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen_MainMenu, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen_MainMenu_screen_init);
    }
}

void ui_event_Utility_Panel_Torch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_flag_modify(ui_Utility_Panel_Torch, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        torch_OFF(e);
    }
}

void ui_event_Utility_Button_closeConfig2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Utility_Panel_SystemInfo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Utility_Button_UpdateFirmware(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ota_update(e);
    }
}

void ui_event_Utility_Button_returnMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_MainMenu, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen_MainMenu_screen_init);
        stopWeatherAnimation(e);
    }
}

void ui_event_Utility_Label_Label27(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_MainMenu, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen_MainMenu_screen_init);
    }
}

void ui_event_Utility_Panel_blindPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        turnonScreen(e);
    }
}

// build funtions

void ui_Screen_Utility_screen_init(void)
{
    ui_Screen_Utility = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Utility, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_Utility, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Utility, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen_Utility, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen_Utility, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Utility_Image_TorchButton = lv_img_create(ui_Screen_Utility);
    lv_img_set_src(ui_Utility_Image_TorchButton, &ui_img_images_torch_png);
    lv_obj_set_width(ui_Utility_Image_TorchButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Utility_Image_TorchButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Utility_Image_TorchButton, 20);
    lv_obj_set_y(ui_Utility_Image_TorchButton, 0);
    lv_obj_set_align(ui_Utility_Image_TorchButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Utility_Image_TorchButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Utility_Image_TorchButton,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Utility_Image_SystemInfoButton = lv_img_create(ui_Screen_Utility);
    lv_img_set_src(ui_Utility_Image_SystemInfoButton, &ui_img_images_systeminfo_png);
    lv_obj_set_width(ui_Utility_Image_SystemInfoButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Utility_Image_SystemInfoButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Utility_Image_SystemInfoButton, -20);
    lv_obj_set_y(ui_Utility_Image_SystemInfoButton, 0);
    lv_obj_set_align(ui_Utility_Image_SystemInfoButton, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Utility_Image_SystemInfoButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Utility_Image_SystemInfoButton,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Utility_Panel_Torch = lv_obj_create(ui_Screen_Utility);
    lv_obj_set_width(ui_Utility_Panel_Torch, lv_pct(100));
    lv_obj_set_height(ui_Utility_Panel_Torch, lv_pct(100));
    lv_obj_set_align(ui_Utility_Panel_Torch, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Utility_Panel_Torch, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Utility_Panel_Torch,
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Utility_Panel_Torch, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Utility_Panel_Torch, LV_DIR_HOR);

    ui_Utility_Label_Label26 = lv_label_create(ui_Utility_Panel_Torch);
    lv_obj_set_width(ui_Utility_Label_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Utility_Label_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Utility_Label_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Utility_Label_Label26, "Touch and Hold to turn off");
    lv_obj_set_style_text_font(ui_Utility_Label_Label26, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Utility_Panel_SystemInfo = lv_obj_create(ui_Screen_Utility);
    lv_obj_set_width(ui_Utility_Panel_SystemInfo, lv_pct(100));
    lv_obj_set_height(ui_Utility_Panel_SystemInfo, lv_pct(100));
    lv_obj_set_align(ui_Utility_Panel_SystemInfo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Utility_Panel_SystemInfo, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Utility_Panel_SystemInfo,
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Utility_Panel_SystemInfo, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Utility_Panel_SystemInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Utility_Panel_SystemInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Utility_Panel_SystemInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Utility_Panel_SystemInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Utility_Panel_SystemInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Utility_Panel_SystemInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Utility_Label_Build = lv_label_create(ui_Utility_Panel_SystemInfo);
    lv_obj_set_width(ui_Utility_Label_Build, 270);
    lv_obj_set_height(ui_Utility_Label_Build, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Utility_Label_Build, 24);
    lv_obj_set_y(ui_Utility_Label_Build, 16);
    lv_obj_set_align(ui_Utility_Label_Build, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_Utility_Label_Build, "TuneBar v1.2.2 (Rahul Mod)\nBuild  : Loading...\nMAC    : Loading...\nFlash  : Loading...");
    lv_obj_set_style_text_color(ui_Utility_Label_Build, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Utility_Label_Build, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Utility_Label_Build, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Utility_Label_Build, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Utility_Label_Build, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Utility_Label_Memory = lv_label_create(ui_Utility_Panel_SystemInfo);
    lv_obj_set_width(ui_Utility_Label_Memory, 270);
    lv_obj_set_height(ui_Utility_Label_Memory, LV_SIZE_CONTENT);
    lv_obj_add_flag(ui_Utility_Label_Memory, LV_OBJ_FLAG_HIDDEN); // Hidden to prevent text overlap

    ui_Utility_Image_qrcode = lv_img_create(ui_Utility_Panel_SystemInfo);
    lv_img_set_src(ui_Utility_Image_qrcode, &ui_img_images_qr_png);
    lv_obj_set_width(ui_Utility_Image_qrcode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Utility_Image_qrcode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Utility_Image_qrcode, 14);
    lv_obj_set_y(ui_Utility_Image_qrcode, 20);
    lv_obj_set_align(ui_Utility_Image_qrcode, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Utility_Image_qrcode, LV_OBJ_FLAG_HIDDEN);     /// Hide QR Code to free space
    lv_obj_clear_flag(ui_Utility_Image_qrcode, LV_OBJ_FLAG_SCROLLABLE);

    ui_Utility_Label_Metrics = lv_label_create(ui_Utility_Panel_SystemInfo);
    lv_obj_set_width(ui_Utility_Label_Metrics, 270);
    lv_obj_set_height(ui_Utility_Label_Metrics, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Utility_Label_Metrics, 310);
    lv_obj_set_y(ui_Utility_Label_Metrics, 16);
    lv_obj_set_align(ui_Utility_Label_Metrics, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_Utility_Label_Metrics, "Wi-Fi : Connecting...\nUptime: 0s\nDRAM  : --\nPSRAM : --\nAudio : ES8311 + ES7210");
    lv_obj_set_style_text_color(ui_Utility_Label_Metrics, lv_color_hex(0x00FF88), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Utility_Label_Metrics, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Utility_Label_Metrics, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Utility_Label_Metrics, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Utility_Button_closeConfig2 = lv_btn_create(ui_Utility_Panel_SystemInfo);
    lv_obj_set_width(ui_Utility_Button_closeConfig2, 36);
    lv_obj_set_height(ui_Utility_Button_closeConfig2, 36);
    lv_obj_set_x(ui_Utility_Button_closeConfig2, -10);
    lv_obj_set_y(ui_Utility_Button_closeConfig2, 10);
    lv_obj_set_align(ui_Utility_Button_closeConfig2, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Utility_Button_closeConfig2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Utility_Button_closeConfig2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Utility_Button_closeConfig2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Utility_Button_closeConfig2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Utility_Button_closeConfig2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Utility_Button_closeConfig2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Utility_Button_closeConfig2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Utility_Label_Label28 = lv_label_create(ui_Utility_Button_closeConfig2);
    lv_obj_set_width(ui_Utility_Label_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Utility_Label_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Utility_Label_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Utility_Label_Label28, "X");
    lv_obj_set_style_text_font(ui_Utility_Label_Label28, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Utility_Button_UpdateFirmware = lv_btn_create(ui_Utility_Panel_SystemInfo);
    lv_obj_set_width(ui_Utility_Button_UpdateFirmware, 233);
    lv_obj_set_height(ui_Utility_Button_UpdateFirmware, 49);
    lv_obj_set_x(ui_Utility_Button_UpdateFirmware, -46);
    lv_obj_set_y(ui_Utility_Button_UpdateFirmware, -16);
    lv_obj_set_align(ui_Utility_Button_UpdateFirmware, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Utility_Button_UpdateFirmware, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Utility_Button_UpdateFirmware, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Utility_Button_UpdateFirmware, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Utility_Button_UpdateFirmware, lv_color_hex(0x72F1FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Utility_Button_UpdateFirmware, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Utility_Button_UpdateFirmware, lv_color_hex(0x3A7C81),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Utility_Button_UpdateFirmware, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Utility_Button_UpdateFirmware, lv_color_hex(0xFC0505),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Utility_Button_UpdateFirmware, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Utility_Button_UpdateFirmware, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Utility_Button_UpdateFirmware, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Utility_Label_Label11 = lv_label_create(ui_Utility_Button_UpdateFirmware);
    lv_obj_set_width(ui_Utility_Label_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Utility_Label_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Utility_Label_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Utility_Label_Label11, "Update");
    lv_obj_set_style_text_color(ui_Utility_Label_Label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Utility_Label_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Utility_Label_Label11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Utility_Label_Label11, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Utility_Label_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Utility_Label_Label11, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Utility_Button_returnMenu = lv_btn_create(ui_Screen_Utility);
    lv_obj_set_width(ui_Utility_Button_returnMenu, 100);
    lv_obj_set_height(ui_Utility_Button_returnMenu, 40);
    lv_obj_set_align(ui_Utility_Button_returnMenu, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Utility_Button_returnMenu, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Utility_Button_returnMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Utility_Button_returnMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Utility_Button_returnMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Utility_Button_returnMenu, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Utility_Button_returnMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Utility_Button_returnMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Utility_Label_Label27 = lv_label_create(ui_Utility_Button_returnMenu);
    lv_obj_set_width(ui_Utility_Label_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Utility_Label_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Utility_Label_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Utility_Label_Label27, "^");
    lv_obj_set_style_text_color(ui_Utility_Label_Label27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Utility_Label_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Utility_Label_Label27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Utility_Label_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Utility_Label_Label27, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Utility_Label_Label27, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Utility_Panel_blindPanel = lv_obj_create(ui_Screen_Utility);
    lv_obj_set_width(ui_Utility_Panel_blindPanel, lv_pct(100));
    lv_obj_set_height(ui_Utility_Panel_blindPanel, lv_pct(100));
    lv_obj_set_align(ui_Utility_Panel_blindPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Utility_Panel_blindPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Utility_Panel_blindPanel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Utility_Panel_blindPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Utility_Panel_blindPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Utility_Panel_blindPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Utility_Panel_blindPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Utility_Panel_blindPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Utility_Panel_blindPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Utility_Image_TorchButton, ui_event_Utility_Image_TorchButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Utility_Image_SystemInfoButton, ui_event_Utility_Image_SystemInfoButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Utility_Panel_Torch, ui_event_Utility_Panel_Torch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Utility_Button_closeConfig2, ui_event_Utility_Button_closeConfig2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Utility_Button_UpdateFirmware, ui_event_Utility_Button_UpdateFirmware, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Utility_Label_Label27, ui_event_Utility_Label_Label27, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Utility_Button_returnMenu, ui_event_Utility_Button_returnMenu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Utility_Panel_blindPanel, ui_event_Utility_Panel_blindPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Utility, ui_event_Screen_Utility, LV_EVENT_ALL, NULL);

}

void ui_Screen_Utility_screen_destroy(void)
{
    if(ui_Screen_Utility) lv_obj_del(ui_Screen_Utility);

    // NULL screen variables
    ui_Screen_Utility = NULL;
    ui_Utility_Image_TorchButton = NULL;
    ui_Utility_Image_SystemInfoButton = NULL;
    ui_Utility_Panel_Torch = NULL;
    ui_Utility_Label_Label26 = NULL;
    ui_Utility_Panel_SystemInfo = NULL;
    ui_Utility_Label_Build = NULL;
    ui_Utility_Label_Memory = NULL;
    ui_Utility_Label_Metrics = NULL;
    ui_Utility_Image_qrcode = NULL;
    ui_Utility_Button_closeConfig2 = NULL;
    ui_Utility_Label_Label28 = NULL;
    ui_Utility_Button_UpdateFirmware = NULL;
    ui_Utility_Label_Label11 = NULL;
    ui_Utility_Button_returnMenu = NULL;
    ui_Utility_Label_Label27 = NULL;
    ui_Utility_Panel_blindPanel = NULL;

}
