// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: tune_bar

#include "../ui.h"

lv_obj_t * ui_Screen_Player = NULL;
lv_obj_t * ui_Player_Textarea_status = NULL;
lv_obj_t * ui_Player_Label_trackNumber = NULL;
lv_obj_t * ui_Player_Container_VolumeControl = NULL;
lv_obj_t * ui_Player_Button_volumeup = NULL;
lv_obj_t * ui_Player_Label_Label1 = NULL;
lv_obj_t * ui_Player_Image_volumemute = NULL;
lv_obj_t * ui_Player_Button_volumedown = NULL;
lv_obj_t * ui_Player_Label_Label2 = NULL;
lv_obj_t * ui_Player_Container_PlaybackControl = NULL;
lv_obj_t * ui_Player_Slider_Progress = NULL;
lv_obj_t * ui_Player_Button_RndRPT = NULL;
lv_obj_t * ui_Player_Label_Label16 = NULL;
lv_obj_t * ui_Player_Button_previous = NULL;
lv_obj_t * ui_Player_Label_Label6 = NULL;
lv_obj_t * ui_Player_Button_skipback = NULL;
lv_obj_t * ui_Player_Label_Label17 = NULL;
lv_obj_t * ui_Player_Button_play = NULL;
lv_obj_t * ui_Player_Label_Label5 = NULL;
lv_obj_t * ui_Player_Button_skipforward = NULL;
lv_obj_t * ui_Player_Label_Label18 = NULL;
lv_obj_t * ui_Player_Button_next = NULL;
lv_obj_t * ui_Player_Label_Label4 = NULL;
lv_obj_t * ui_Player_Label_ElapseTime = NULL;
lv_obj_t * ui_Player_Label_RemainTime = NULL;
lv_obj_t * ui_Player_Container_albumCover = NULL;
lv_obj_t * ui_Player_Button_returnMenu = NULL;
lv_obj_t * ui_Player_Label_Label7 = NULL;
lv_obj_t * ui_Player_Container_status1 = NULL;
lv_obj_t * ui_Player_Label_Battery = NULL;
lv_obj_t * ui_Player_Label_WiFi = NULL;
lv_obj_t * ui_Player_Label_SDcard = NULL;
lv_obj_t * ui_Player_Panel_blindPanel = NULL;
lv_obj_t * ui_Player_Button_Catalog = NULL;
lv_obj_t * ui_Player_Label_Catalog = NULL;
// event funtions
void ui_event_Screen_Player(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen_MainMenu, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen_MainMenu_screen_init);
    }
}

void ui_event_Player_Button_volumeup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        volumeup(e);
    }
}

void ui_event_Player_Image_volumemute(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        volumemute(e);
    }
}

void ui_event_Player_Button_volumedown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        volumedown(e);
    }
}

void ui_event_Player_Slider_Progress(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        playseek(e);
    }
    if(event_code == LV_EVENT_PRESSED) {
        SeekingNow(e);
    }
}

void ui_event_Player_Button_RndRPT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        togglePlayingMode(e);
    }
}

void ui_event_Player_Button_previous(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        previoustrack(e);
    }
}

void ui_event_Player_Button_skipback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        fastReverse5(e);
    }
}

void ui_event_Player_Button_play(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        playpause(e);
    }
}

void ui_event_Player_Button_skipforward(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        fastForward5(e);
    }
}

void ui_event_Player_Button_next(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        nexttrack(e);
    }
}

void ui_event_Player_Button_returnMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_MainMenu, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_Screen_MainMenu_screen_init);
    }
}

void ui_event_Player_Panel_blindPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        turnonScreen(e);
    }
}

extern void on_catalog_button_clicked(void);
void ui_event_Player_Button_Catalog(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_catalog_button_clicked();
    }
}

// build funtions

void ui_Screen_Player_screen_init(void)
{
    ui_Screen_Player = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Player, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_Player, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Player, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Screen_Player, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Screen_Player, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Screen_Player, lv_color_hex(0xFF0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen_Player, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen_Player, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Button_Catalog = lv_btn_create(ui_Screen_Player);
    lv_obj_set_width(ui_Player_Button_Catalog, 64);
    lv_obj_set_height(ui_Player_Button_Catalog, 22);
    lv_obj_set_x(ui_Player_Button_Catalog, 180);
    lv_obj_set_y(ui_Player_Button_Catalog, 3);
    lv_obj_set_align(ui_Player_Button_Catalog, LV_ALIGN_TOP_LEFT);
    lv_obj_set_style_bg_color(ui_Player_Button_Catalog, lv_color_hex(0x102A40), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Player_Button_Catalog, lv_color_hex(0x00E5FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Player_Button_Catalog, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Player_Button_Catalog, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_Player_Button_Catalog, ui_event_Player_Button_Catalog, LV_EVENT_ALL, NULL);

    ui_Player_Label_Catalog = lv_label_create(ui_Player_Button_Catalog);
    lv_obj_set_align(ui_Player_Label_Catalog, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Player_Label_Catalog, LV_SYMBOL_AUDIO " FM");
    lv_obj_set_style_text_color(ui_Player_Label_Catalog, lv_color_hex(0x00E5FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Player_Label_Catalog, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Label_trackNumber = lv_label_create(ui_Screen_Player);
    lv_obj_set_width(ui_Player_Label_trackNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Player_Label_trackNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Player_Label_trackNumber, 252);
    lv_obj_set_y(ui_Player_Label_trackNumber, 6);
    lv_obj_set_align(ui_Player_Label_trackNumber, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_Player_Label_trackNumber, "");
    lv_obj_set_style_text_color(ui_Player_Label_trackNumber, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Label_trackNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Player_Label_trackNumber, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Player_Label_trackNumber, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Textarea_status = lv_textarea_create(ui_Screen_Player);
    lv_obj_set_width(ui_Player_Textarea_status, 400);
    lv_obj_set_height(ui_Player_Textarea_status, 76);
    lv_obj_set_x(ui_Player_Textarea_status, 175);
    lv_obj_set_y(ui_Player_Textarea_status, 26);
    lv_obj_set_align(ui_Player_Textarea_status, LV_ALIGN_TOP_LEFT);
    lv_textarea_set_max_length(ui_Player_Textarea_status, 1024);
    lv_obj_add_flag(ui_Player_Textarea_status, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_Player_Textarea_status,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_scroll_dir(ui_Player_Textarea_status, LV_DIR_VER);
    lv_obj_set_scrollbar_mode(ui_Player_Textarea_status, LV_SCROLLBAR_MODE_AUTO);
    lv_obj_set_style_text_color(ui_Player_Textarea_status, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Textarea_status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Player_Textarea_status, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Player_Textarea_status, &ui_font_NotoSanThai20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Player_Textarea_status, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Player_Textarea_status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Player_Textarea_status, lv_color_hex(0x6C4902), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Player_Textarea_status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Container_VolumeControl = lv_obj_create(ui_Screen_Player);
    lv_obj_remove_style_all(ui_Player_Container_VolumeControl);
    lv_obj_set_width(ui_Player_Container_VolumeControl, 60);
    lv_obj_set_height(ui_Player_Container_VolumeControl, lv_pct(100));
    lv_obj_set_align(ui_Player_Container_VolumeControl, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Player_Container_VolumeControl, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Player_Container_VolumeControl, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Player_Container_VolumeControl, 127, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Player_Container_VolumeControl, lv_color_hex(0xFFFFFF),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Player_Container_VolumeControl, 127, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Player_Container_VolumeControl, 127, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Player_Container_VolumeControl, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Player_Container_VolumeControl, lv_color_hex(0xFFFFFF),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Player_Container_VolumeControl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Player_Container_VolumeControl, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Player_Container_VolumeControl, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Player_Container_VolumeControl, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Container_VolumeControl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Button_volumeup = lv_btn_create(ui_Player_Container_VolumeControl);
    lv_obj_set_width(ui_Player_Button_volumeup, 50);
    lv_obj_set_height(ui_Player_Button_volumeup, 50);
    lv_obj_set_x(ui_Player_Button_volumeup, 0);
    lv_obj_set_y(ui_Player_Button_volumeup, 5);
    lv_obj_set_align(ui_Player_Button_volumeup, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Player_Button_volumeup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Player_Button_volumeup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Player_Button_volumeup, lv_color_hex(0x84FE9B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Player_Button_volumeup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Player_Button_volumeup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Player_Button_volumeup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Player_Button_volumeup, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Player_Button_volumeup, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Player_Button_volumeup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Player_Button_volumeup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Label_Label1 = lv_label_create(ui_Player_Button_volumeup);
    lv_obj_set_width(ui_Player_Label_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Player_Label_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Player_Label_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Player_Label_Label1, "+");
    lv_obj_set_style_text_color(ui_Player_Label_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Label_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Image_volumemute = lv_img_create(ui_Player_Container_VolumeControl);
    lv_img_set_src(ui_Player_Image_volumemute, &ui_img_images_mute_png);
    lv_obj_set_width(ui_Player_Image_volumemute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Player_Image_volumemute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Player_Image_volumemute, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Player_Image_volumemute, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Player_Image_volumemute, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Player_Image_volumemute, 150);

    ui_Player_Button_volumedown = lv_btn_create(ui_Player_Container_VolumeControl);
    lv_obj_set_width(ui_Player_Button_volumedown, 50);
    lv_obj_set_height(ui_Player_Button_volumedown, 50);
    lv_obj_set_x(ui_Player_Button_volumedown, 0);
    lv_obj_set_y(ui_Player_Button_volumedown, -5);
    lv_obj_set_align(ui_Player_Button_volumedown, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Player_Button_volumedown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Player_Button_volumedown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Player_Button_volumedown, lv_color_hex(0x84FE9B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Player_Button_volumedown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Player_Button_volumedown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Player_Button_volumedown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Player_Button_volumedown, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Player_Button_volumedown, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Player_Button_volumedown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Player_Button_volumedown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Label_Label2 = lv_label_create(ui_Player_Button_volumedown);
    lv_obj_set_width(ui_Player_Label_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Player_Label_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Player_Label_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Player_Label_Label2, "-");
    lv_obj_set_style_text_color(ui_Player_Label_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Label_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Container_PlaybackControl = lv_obj_create(ui_Screen_Player);
    lv_obj_remove_style_all(ui_Player_Container_PlaybackControl);
    lv_obj_set_width(ui_Player_Container_PlaybackControl, 400);
    lv_obj_set_height(ui_Player_Container_PlaybackControl, 70);
    lv_obj_set_x(ui_Player_Container_PlaybackControl, 57);
    lv_obj_set_y(ui_Player_Container_PlaybackControl, -1);
    lv_obj_set_align(ui_Player_Container_PlaybackControl, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Player_Container_PlaybackControl, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Player_Container_PlaybackControl, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Container_PlaybackControl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Slider_Progress = lv_slider_create(ui_Player_Container_PlaybackControl);
    lv_slider_set_value(ui_Player_Slider_Progress, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Player_Slider_Progress) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_Player_Slider_Progress, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Player_Slider_Progress, 250);
    lv_obj_set_height(ui_Player_Slider_Progress, 3);
    lv_obj_set_x(ui_Player_Slider_Progress, 0);
    lv_obj_set_y(ui_Player_Slider_Progress, 7);
    lv_obj_set_align(ui_Player_Slider_Progress, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_Player_Slider_Progress, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Player_Slider_Progress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Player_Slider_Progress, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Player_Slider_Progress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Player_Slider_Progress, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Player_Slider_Progress, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Player_Slider_Progress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Player_Slider_Progress, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Player_Slider_Progress, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Player_Slider_Progress, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Player_Slider_Progress, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Player_Slider_Progress, lv_color_hex(0x777777), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Player_Slider_Progress, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Player_Slider_Progress, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Player_Slider_Progress, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Player_Slider_Progress, lv_color_hex(0x777777), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Player_Slider_Progress, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Player_Slider_Progress, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Player_Slider_Progress, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Player_Slider_Progress, LV_BORDER_SIDE_FULL, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Player_Button_RndRPT = lv_btn_create(ui_Player_Container_PlaybackControl);
    lv_obj_set_width(ui_Player_Button_RndRPT, 50);
    lv_obj_set_height(ui_Player_Button_RndRPT, 50);
    lv_obj_set_x(ui_Player_Button_RndRPT, 0);
    lv_obj_set_y(ui_Player_Button_RndRPT, 8);
    lv_obj_set_align(ui_Player_Button_RndRPT, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Player_Button_RndRPT, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Player_Button_RndRPT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Player_Button_RndRPT, lv_color_hex(0xFED272), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Player_Button_RndRPT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Player_Button_RndRPT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Player_Button_RndRPT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Player_Button_RndRPT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Button_RndRPT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_ext_click_area(ui_Player_Button_RndRPT, 20);

    ui_Player_Label_Label16 = lv_label_create(ui_Player_Button_RndRPT);
    lv_obj_set_width(ui_Player_Label_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Player_Label_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Player_Label_Label16, 0);
    lv_obj_set_y(ui_Player_Label_Label16, 4);
    lv_obj_set_align(ui_Player_Label_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Player_Label_Label16, "R");
    lv_obj_set_style_text_color(ui_Player_Label_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Label_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Button_previous = lv_btn_create(ui_Player_Container_PlaybackControl);
    lv_obj_set_width(ui_Player_Button_previous, 45);
    lv_obj_set_height(ui_Player_Button_previous, 45);
    lv_obj_set_x(ui_Player_Button_previous, -120);
    lv_obj_set_y(ui_Player_Button_previous, 10);
    lv_obj_set_align(ui_Player_Button_previous, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Player_Button_previous, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Player_Button_previous, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Player_Button_previous, lv_color_hex(0xFED272), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Player_Button_previous, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Player_Button_previous, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Player_Button_previous, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Player_Button_previous, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Button_previous, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Label_Label6 = lv_label_create(ui_Player_Button_previous);
    lv_obj_set_width(ui_Player_Label_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Player_Label_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Player_Label_Label6, 0);
    lv_obj_set_y(ui_Player_Label_Label6, 4);
    lv_obj_set_align(ui_Player_Label_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Player_Label_Label6, "<");
    lv_obj_set_style_text_color(ui_Player_Label_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Label_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Button_skipback = lv_btn_create(ui_Player_Container_PlaybackControl);
    lv_obj_set_width(ui_Player_Button_skipback, 45);
    lv_obj_set_height(ui_Player_Button_skipback, 45);
    lv_obj_set_x(ui_Player_Button_skipback, -60);
    lv_obj_set_y(ui_Player_Button_skipback, 10);
    lv_obj_set_align(ui_Player_Button_skipback, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Player_Button_skipback, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Player_Button_skipback, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Player_Button_skipback, lv_color_hex(0xFED272), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Player_Button_skipback, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Player_Button_skipback, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Player_Button_skipback, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Player_Button_skipback, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Button_skipback, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Label_Label17 = lv_label_create(ui_Player_Button_skipback);
    lv_obj_set_width(ui_Player_Label_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Player_Label_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Player_Label_Label17, 0);
    lv_obj_set_y(ui_Player_Label_Label17, 4);
    lv_obj_set_align(ui_Player_Label_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Player_Label_Label17, "<<");
    lv_obj_set_style_text_color(ui_Player_Label_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Label_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Button_play = lv_btn_create(ui_Player_Container_PlaybackControl);
    lv_obj_set_width(ui_Player_Button_play, 45);
    lv_obj_set_height(ui_Player_Button_play, 45);
    lv_obj_set_x(ui_Player_Button_play, 0);
    lv_obj_set_y(ui_Player_Button_play, 10);
    lv_obj_set_align(ui_Player_Button_play, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Player_Button_play, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Player_Button_play, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Player_Button_play, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Player_Button_play, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Player_Button_play, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Player_Button_play, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Player_Button_play, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Label_Label5 = lv_label_create(ui_Player_Button_play);
    lv_obj_set_width(ui_Player_Label_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Player_Label_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Player_Label_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Player_Label_Label5, ">");
    lv_obj_set_style_text_color(ui_Player_Label_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Label_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Button_skipforward = lv_btn_create(ui_Player_Container_PlaybackControl);
    lv_obj_set_width(ui_Player_Button_skipforward, 45);
    lv_obj_set_height(ui_Player_Button_skipforward, 45);
    lv_obj_set_x(ui_Player_Button_skipforward, 60);
    lv_obj_set_y(ui_Player_Button_skipforward, 10);
    lv_obj_set_align(ui_Player_Button_skipforward, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Player_Button_skipforward, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Player_Button_skipforward, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Player_Button_skipforward, lv_color_hex(0xFED272), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Player_Button_skipforward, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Player_Button_skipforward, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Player_Button_skipforward, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Label_Label18 = lv_label_create(ui_Player_Button_skipforward);
    lv_obj_set_width(ui_Player_Label_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Player_Label_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Player_Label_Label18, 0);
    lv_obj_set_y(ui_Player_Label_Label18, 4);
    lv_obj_set_align(ui_Player_Label_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Player_Label_Label18, ">>");
    lv_obj_set_style_text_color(ui_Player_Label_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Label_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Button_next = lv_btn_create(ui_Player_Container_PlaybackControl);
    lv_obj_set_width(ui_Player_Button_next, 45);
    lv_obj_set_height(ui_Player_Button_next, 45);
    lv_obj_set_x(ui_Player_Button_next, 120);
    lv_obj_set_y(ui_Player_Button_next, 10);
    lv_obj_set_align(ui_Player_Button_next, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Player_Button_next, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Player_Button_next, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Player_Button_next, lv_color_hex(0xFED272), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Player_Button_next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Player_Button_next, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Player_Button_next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Label_Label4 = lv_label_create(ui_Player_Button_next);
    lv_obj_set_width(ui_Player_Label_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Player_Label_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Player_Label_Label4, 0);
    lv_obj_set_y(ui_Player_Label_Label4, 4);
    lv_obj_set_align(ui_Player_Label_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Player_Label_Label4, ">");
    lv_obj_set_style_text_color(ui_Player_Label_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Label_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Label_ElapseTime = lv_label_create(ui_Player_Container_PlaybackControl);
    lv_obj_set_width(ui_Player_Label_ElapseTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Player_Label_ElapseTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Player_Label_ElapseTime, -335);
    lv_obj_set_y(ui_Player_Label_ElapseTime, -2);
    lv_obj_set_align(ui_Player_Label_ElapseTime, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Player_Label_ElapseTime, "00:00:00");
    lv_obj_set_style_text_color(ui_Player_Label_ElapseTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Label_ElapseTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Player_Label_ElapseTime, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Player_Label_ElapseTime, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Label_RemainTime = lv_label_create(ui_Player_Container_PlaybackControl);
    lv_obj_set_width(ui_Player_Label_RemainTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Player_Label_RemainTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Player_Label_RemainTime, 335);
    lv_obj_set_y(ui_Player_Label_RemainTime, -2);
    lv_label_set_text(ui_Player_Label_RemainTime, "00:00:00");
    lv_obj_set_style_text_color(ui_Player_Label_RemainTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Label_RemainTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Player_Label_RemainTime, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Player_Label_RemainTime, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Container_albumCover = lv_obj_create(ui_Screen_Player);
    lv_obj_remove_style_all(ui_Player_Container_albumCover);
    lv_obj_set_width(ui_Player_Container_albumCover, 172);
    lv_obj_set_height(ui_Player_Container_albumCover, 172);
    lv_obj_set_align(ui_Player_Container_albumCover, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Player_Container_albumCover, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Player_Container_albumCover, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Player_Container_albumCover, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Button_returnMenu = lv_btn_create(ui_Screen_Player);
    lv_obj_set_width(ui_Player_Button_returnMenu, 40);
    lv_obj_set_height(ui_Player_Button_returnMenu, 40);
    lv_obj_set_x(ui_Player_Button_returnMenu, -62);
    lv_obj_set_y(ui_Player_Button_returnMenu, 0);
    lv_obj_set_align(ui_Player_Button_returnMenu, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Player_Button_returnMenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Player_Button_returnMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Player_Button_returnMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Player_Button_returnMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Player_Button_returnMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Player_Button_returnMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Label_Label7 = lv_label_create(ui_Player_Button_returnMenu);
    lv_obj_set_width(ui_Player_Label_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Player_Label_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Player_Label_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Player_Label_Label7, "^");
    lv_obj_set_style_text_color(ui_Player_Label_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Label_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Player_Label_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Player_Label_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Player_Label_Label7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Player_Label_Label7, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Container_status1 = lv_obj_create(ui_Screen_Player);
    lv_obj_remove_style_all(ui_Player_Container_status1);
    lv_obj_set_width(ui_Player_Container_status1, 30);
    lv_obj_set_height(ui_Player_Container_status1, 100);
    lv_obj_set_x(ui_Player_Container_status1, -64);
    lv_obj_set_y(ui_Player_Container_status1, -4);
    lv_obj_set_align(ui_Player_Container_status1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_Player_Container_status1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Player_Container_status1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Label_Battery = lv_label_create(ui_Player_Container_status1);
    lv_obj_set_width(ui_Player_Label_Battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Player_Label_Battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Player_Label_Battery, 0);
    lv_obj_set_y(ui_Player_Label_Battery, -70);
    lv_obj_set_align(ui_Player_Label_Battery, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Player_Label_Battery, "B");
    lv_obj_set_style_text_color(ui_Player_Label_Battery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Label_Battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Label_WiFi = lv_label_create(ui_Player_Container_status1);
    lv_obj_set_width(ui_Player_Label_WiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Player_Label_WiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Player_Label_WiFi, 0);
    lv_obj_set_y(ui_Player_Label_WiFi, -26);
    lv_obj_set_align(ui_Player_Label_WiFi, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Player_Label_WiFi, "W");
    lv_obj_set_style_text_color(ui_Player_Label_WiFi, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Label_WiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Label_SDcard = lv_label_create(ui_Player_Container_status1);
    lv_obj_set_width(ui_Player_Label_SDcard, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Player_Label_SDcard, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Player_Label_SDcard, 0);
    lv_obj_set_y(ui_Player_Label_SDcard, 2);
    lv_obj_set_align(ui_Player_Label_SDcard, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Player_Label_SDcard, "S");
    lv_obj_set_style_text_color(ui_Player_Label_SDcard, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Player_Label_SDcard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Player_Panel_blindPanel = lv_obj_create(ui_Screen_Player);
    lv_obj_set_width(ui_Player_Panel_blindPanel, lv_pct(100));
    lv_obj_set_height(ui_Player_Panel_blindPanel, lv_pct(100));
    lv_obj_set_align(ui_Player_Panel_blindPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Player_Panel_blindPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Player_Panel_blindPanel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Player_Panel_blindPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Player_Panel_blindPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Player_Panel_blindPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Player_Panel_blindPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Player_Panel_blindPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Player_Panel_blindPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Player_Button_volumeup, ui_event_Player_Button_volumeup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Player_Image_volumemute, ui_event_Player_Image_volumemute, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Player_Button_volumedown, ui_event_Player_Button_volumedown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Player_Slider_Progress, ui_event_Player_Slider_Progress, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Player_Button_RndRPT, ui_event_Player_Button_RndRPT, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Player_Button_previous, ui_event_Player_Button_previous, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Player_Button_skipback, ui_event_Player_Button_skipback, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Player_Button_play, ui_event_Player_Button_play, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Player_Button_skipforward, ui_event_Player_Button_skipforward, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Player_Button_next, ui_event_Player_Button_next, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Player_Button_returnMenu, ui_event_Player_Button_returnMenu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Player_Panel_blindPanel, ui_event_Player_Panel_blindPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen_Player, ui_event_Screen_Player, LV_EVENT_ALL, NULL);

}

void ui_Screen_Player_screen_destroy(void)
{
    if(ui_Screen_Player) lv_obj_del(ui_Screen_Player);

    // NULL screen variables
    ui_Screen_Player = NULL;
    ui_Player_Textarea_status = NULL;
    ui_Player_Label_trackNumber = NULL;
    ui_Player_Container_VolumeControl = NULL;
    ui_Player_Button_volumeup = NULL;
    ui_Player_Label_Label1 = NULL;
    ui_Player_Image_volumemute = NULL;
    ui_Player_Button_volumedown = NULL;
    ui_Player_Label_Label2 = NULL;
    ui_Player_Container_PlaybackControl = NULL;
    ui_Player_Slider_Progress = NULL;
    ui_Player_Button_RndRPT = NULL;
    ui_Player_Label_Label16 = NULL;
    ui_Player_Button_previous = NULL;
    ui_Player_Label_Label6 = NULL;
    ui_Player_Button_skipback = NULL;
    ui_Player_Label_Label17 = NULL;
    ui_Player_Button_play = NULL;
    ui_Player_Label_Label5 = NULL;
    ui_Player_Button_skipforward = NULL;
    ui_Player_Label_Label18 = NULL;
    ui_Player_Button_next = NULL;
    ui_Player_Label_Label4 = NULL;
    ui_Player_Label_ElapseTime = NULL;
    ui_Player_Label_RemainTime = NULL;
    ui_Player_Container_albumCover = NULL;
    ui_Player_Button_returnMenu = NULL;
    ui_Player_Label_Label7 = NULL;
    ui_Player_Container_status1 = NULL;
    ui_Player_Label_Battery = NULL;
    ui_Player_Label_WiFi = NULL;
    ui_Player_Label_SDcard = NULL;
    ui_Player_Panel_blindPanel = NULL;
    ui_Player_Button_Catalog = NULL;
    ui_Player_Label_Catalog = NULL;

}
