// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: tune_bar

#ifndef UI_SCREEN_PLAYER_H
#define UI_SCREEN_PLAYER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Player
extern void ui_Screen_Player_screen_init(void);
extern void ui_Screen_Player_screen_destroy(void);
extern void ui_event_Screen_Player(lv_event_t * e);
extern lv_obj_t * ui_Screen_Player;
extern lv_obj_t * ui_Player_Textarea_status;
extern lv_obj_t * ui_Player_Label_trackNumber;
extern lv_obj_t * ui_Player_Container_VolumeControl;
extern void ui_event_Player_Button_volumeup(lv_event_t * e);
extern lv_obj_t * ui_Player_Button_volumeup;
extern lv_obj_t * ui_Player_Label_Label1;
extern void ui_event_Player_Image_volumemute(lv_event_t * e);
extern lv_obj_t * ui_Player_Image_volumemute;
extern void ui_event_Player_Button_volumedown(lv_event_t * e);
extern lv_obj_t * ui_Player_Button_volumedown;
extern lv_obj_t * ui_Player_Label_Label2;
extern lv_obj_t * ui_Player_Container_PlaybackControl;
extern void ui_event_Player_Slider_Progress(lv_event_t * e);
extern lv_obj_t * ui_Player_Slider_Progress;
extern void ui_event_Player_Button_RndRPT(lv_event_t * e);
extern lv_obj_t * ui_Player_Button_RndRPT;
extern lv_obj_t * ui_Player_Label_Label16;
extern void ui_event_Player_Button_previous(lv_event_t * e);
extern lv_obj_t * ui_Player_Button_previous;
extern lv_obj_t * ui_Player_Label_Label6;
extern void ui_event_Player_Button_skipback(lv_event_t * e);
extern lv_obj_t * ui_Player_Button_skipback;
extern lv_obj_t * ui_Player_Label_Label17;
extern void ui_event_Player_Button_play(lv_event_t * e);
extern lv_obj_t * ui_Player_Button_play;
extern lv_obj_t * ui_Player_Label_Label5;
extern void ui_event_Player_Button_skipforward(lv_event_t * e);
extern lv_obj_t * ui_Player_Button_skipforward;
extern lv_obj_t * ui_Player_Label_Label18;
extern void ui_event_Player_Button_next(lv_event_t * e);
extern lv_obj_t * ui_Player_Button_next;
extern lv_obj_t * ui_Player_Label_Label4;
extern lv_obj_t * ui_Player_Label_ElapseTime;
extern lv_obj_t * ui_Player_Label_RemainTime;
extern lv_obj_t * ui_Player_Container_albumCover;
extern void ui_event_Player_Button_returnMenu(lv_event_t * e);
extern lv_obj_t * ui_Player_Button_returnMenu;
extern lv_obj_t * ui_Player_Label_Label7;
extern lv_obj_t * ui_Player_Container_status1;
extern lv_obj_t * ui_Player_Label_Battery;
extern lv_obj_t * ui_Player_Label_WiFi;
extern lv_obj_t * ui_Player_Label_SDcard;
extern void ui_event_Player_Panel_blindPanel(lv_event_t * e);
extern lv_obj_t * ui_Player_Panel_blindPanel;
extern lv_obj_t * ui_Player_Button_Catalog;
extern lv_obj_t * ui_Player_Label_Catalog;
extern void ui_event_Player_Button_Catalog(lv_event_t * e);
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

