// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: tune_bar

#ifndef UI_SCREEN_UTILITY_H
#define UI_SCREEN_UTILITY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Utility
extern void ui_Screen_Utility_screen_init(void);
extern void ui_Screen_Utility_screen_destroy(void);
extern void ui_event_Screen_Utility(lv_event_t * e);
extern lv_obj_t * ui_Screen_Utility;
extern void ui_event_Utility_Image_TorchButton(lv_event_t * e);
extern lv_obj_t * ui_Utility_Image_TorchButton;
extern void ui_event_Utility_Image_SystemInfoButton(lv_event_t * e);
extern lv_obj_t * ui_Utility_Image_SystemInfoButton;
extern void ui_event_Utility_Panel_Torch(lv_event_t * e);
extern lv_obj_t * ui_Utility_Panel_Torch;
extern lv_obj_t * ui_Utility_Label_Label26;
extern lv_obj_t * ui_Utility_Panel_SystemInfo;
extern lv_obj_t * ui_Utility_Label_Build;
extern lv_obj_t * ui_Utility_Label_Memory;
extern lv_obj_t * ui_Utility_Label_Metrics;
extern lv_obj_t * ui_Utility_Image_qrcode;
extern void ui_event_Utility_Button_closeConfig2(lv_event_t * e);
extern lv_obj_t * ui_Utility_Button_closeConfig2;
extern lv_obj_t * ui_Utility_Label_Label28;
extern void ui_event_Utility_Button_UpdateFirmware(lv_event_t * e);
extern lv_obj_t * ui_Utility_Button_UpdateFirmware;
extern lv_obj_t * ui_Utility_Label_Label11;
extern void ui_event_Utility_Button_returnMenu(lv_event_t * e);
extern lv_obj_t * ui_Utility_Button_returnMenu;
extern void ui_event_Utility_Label_Label27(lv_event_t * e);
extern lv_obj_t * ui_Utility_Label_Label27;
extern void ui_event_Utility_Panel_blindPanel(lv_event_t * e);
extern lv_obj_t * ui_Utility_Panel_blindPanel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

