// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: tune_bar

#ifndef UI_SCREEN_INFO_H
#define UI_SCREEN_INFO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Info
extern void ui_Screen_Info_screen_init(void);
extern void ui_Screen_Info_screen_destroy(void);
extern void ui_event_Screen_Info(lv_event_t * e);
extern lv_obj_t * ui_Screen_Info;
extern lv_obj_t * ui_Info_Label_BattStatus;
extern void ui_event_Info_Panel_Clock(lv_event_t * e);
extern lv_obj_t * ui_Info_Panel_Clock;
extern lv_obj_t * ui_Info_Image_hour0;
extern lv_obj_t * ui_Info_Image_hour1;
extern lv_obj_t * ui_Info_Image_colon0;
extern lv_obj_t * ui_Info_Image_minute0;
extern lv_obj_t * ui_Info_Image_minute1;
extern lv_obj_t * ui_Info_Image_colon1;
extern lv_obj_t * ui_Info_Image_second0;
extern lv_obj_t * ui_Info_Image_second1;
extern lv_obj_t * ui_Info_Label_DateNixie;
extern void ui_event_Info_Panel_Weather(lv_event_t * e);
extern lv_obj_t * ui_Info_Panel_Weather;
extern lv_obj_t * ui_Info_Image_Home;
extern lv_obj_t * ui_Info_Image_Turbine;
extern lv_obj_t * ui_Info_Image_Propeller;
extern lv_obj_t * ui_Info_Image_WeatherIcon;
extern lv_obj_t * ui_Info_Image_cat;
extern lv_obj_t * ui_Info_Image_dog;
extern lv_obj_t * ui_Info_Container_WeatherDetail;
extern lv_obj_t * ui_Info_Label_Detail;
extern lv_obj_t * ui_Info_Label_Temp;
extern void ui_event_Info_Label_LastUpdated(lv_event_t * e);
extern lv_obj_t * ui_Info_Label_LastUpdated;
extern void ui_event_Info_Label_DateTime(lv_event_t * e);
extern lv_obj_t * ui_Info_Label_DateTime;
extern lv_obj_t * ui_Info_Label_Label23;
extern void ui_event_Info_Panel_AQI(lv_event_t * e);
extern lv_obj_t * ui_Info_Panel_AQI;
extern lv_obj_t * ui_Info_Label_AQIvalue;
extern lv_obj_t * ui_Info_Label_Label24;
extern lv_obj_t * ui_Info_Label_AQIdominant;
extern lv_obj_t * ui_Info_Label_AQIrate;
extern lv_obj_t * ui_Info_Label_AQIlocation;
extern lv_obj_t * ui_Info_Image_AQIimage;
extern void ui_event_Info_Button_returnMenu(lv_event_t * e);
extern lv_obj_t * ui_Info_Button_returnMenu;
extern lv_obj_t * ui_Info_Label_Label21;
extern void ui_event_Info_Button_infoPanelLeft(lv_event_t * e);
extern lv_obj_t * ui_Info_Button_infoPanelLeft;
extern lv_obj_t * ui_Info_Label_Label19;
extern void ui_event_Info_Button_infoPanelRight(lv_event_t * e);
extern lv_obj_t * ui_Info_Button_infoPanelRight;
extern lv_obj_t * ui_Info_Label_Label22;
extern void ui_event_Info_Panel_blindPanel(lv_event_t * e);
extern lv_obj_t * ui_Info_Panel_blindPanel;
extern lv_obj_t * ui_Info_Panel_Alarm;
extern void alarm_ui_init(lv_obj_t * parent);
extern void alarm_ui_show(void);
extern void alarm_ui_refresh(void);
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

