// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: tune_bar

#ifndef _TUNE_BAR_UI_H
#define _TUNE_BAR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen_Boot.h"
#include "screens/ui_Screen_MainMenu.h"
#include "screens/ui_Screen_Info.h"
#include "screens/ui_Screen_Player.h"
#include "screens/ui_Screen_Utility.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * bounce_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * blink_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * spin_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_images_tunebar_banner_png);    // assets/images/tunebar_banner.png
LV_IMG_DECLARE(ui_img_images_livestreaming_png);    // assets/images/livestreaming.png
LV_IMG_DECLARE(ui_img_images_music_png);    // assets/images/music.png
LV_IMG_DECLARE(ui_img_music_local_png);     // assets/images/music_local.png
LV_IMG_DECLARE(ui_img_music_lan_png);       // assets/images/music_lan.png
LV_IMG_DECLARE(ui_img_images_assistant_png);    // assets/images/assistant.png
LV_IMG_DECLARE(ui_img_images_climate_png);    // assets/images/climate.png
LV_IMG_DECLARE(ui_img_images_utility_png);    // assets/images/utility.png
LV_IMG_DECLARE(ui_img_images_settings_png);    // assets/images/settings.png
LV_IMG_DECLARE(ui_img_images_globe_png);    // assets/images/globe.png
LV_IMG_DECLARE(ui_img_images_timezone_png);    // assets/images/timezone.png
LV_IMG_DECLARE(ui_img_images_button_png);    // assets/images/button.png
LV_IMG_DECLARE(ui_img_numbers_0_png);    // assets/numbers/0.png
LV_IMG_DECLARE(ui_img_numbers_colon_png);    // assets/numbers/colon.png
LV_IMG_DECLARE(ui_img_weather_home_sunny_png);    // assets/weather/home_sunny.png
LV_IMG_DECLARE(ui_img_weather_stack_png);    // assets/weather/stack.png
LV_IMG_DECLARE(ui_img_weather_propeller_png);    // assets/weather/propeller.png
LV_IMG_DECLARE(ui_img_custom_cat_right1_png);    // assets/custom/cat_right1.png
LV_IMG_DECLARE(ui_img_custom_dog_left1_png);    // assets/custom/dog_left1.png
LV_IMG_DECLARE(ui_img_images_mute_png);    // assets/images/mute.png
LV_IMG_DECLARE(ui_img_images_torch_png);    // assets/images/torch.png
LV_IMG_DECLARE(ui_img_images_systeminfo_png);    // assets/images/systeminfo.png
LV_IMG_DECLARE(ui_img_images_vaandcobbanner_png);    // assets/images/vaandcobBanner.png
LV_IMG_DECLARE(ui_img_images_qr_png);    // assets/images/qr.png
LV_IMG_DECLARE(ui_img_aqi_good_png);    // assets/aqi/good.png
LV_IMG_DECLARE(ui_img_aqi_hazardous_png);    // assets/aqi/hazardous.png
LV_IMG_DECLARE(ui_img_aqi_moderate_png);    // assets/aqi/moderate.png
LV_IMG_DECLARE(ui_img_aqi_sensitive_png);    // assets/aqi/sensitive.png
LV_IMG_DECLARE(ui_img_aqi_unhealthy_png);    // assets/aqi/unhealthy.png
LV_IMG_DECLARE(ui_img_aqi_very_unhealthy_png);    // assets/aqi/very_unhealthy.png
LV_IMG_DECLARE(ui_img_custom_cat_left1_png);    // assets/custom/cat_left1.png
LV_IMG_DECLARE(ui_img_custom_cat_left2_png);    // assets/custom/cat_left2.png
LV_IMG_DECLARE(ui_img_custom_cat_right2_png);    // assets/custom/cat_right2.png
LV_IMG_DECLARE(ui_img_custom_dog_left2_png);    // assets/custom/dog_left2.png
LV_IMG_DECLARE(ui_img_custom_dog_right1_png);    // assets/custom/dog_right1.png
LV_IMG_DECLARE(ui_img_custom_dog_right2_png);    // assets/custom/dog_right2.png
LV_IMG_DECLARE(ui_img_numbers_1_png);    // assets/numbers/1.png
LV_IMG_DECLARE(ui_img_numbers_2_png);    // assets/numbers/2.png
LV_IMG_DECLARE(ui_img_numbers_3_png);    // assets/numbers/3.png
LV_IMG_DECLARE(ui_img_numbers_4_png);    // assets/numbers/4.png
LV_IMG_DECLARE(ui_img_numbers_5_png);    // assets/numbers/5.png
LV_IMG_DECLARE(ui_img_numbers_6_png);    // assets/numbers/6.png
LV_IMG_DECLARE(ui_img_numbers_7_png);    // assets/numbers/7.png
LV_IMG_DECLARE(ui_img_numbers_8_png);    // assets/numbers/8.png
LV_IMG_DECLARE(ui_img_numbers_9_png);    // assets/numbers/9.png
LV_IMG_DECLARE(ui_img_numbers_minus_png);    // assets/numbers/minus.png
LV_IMG_DECLARE(ui_img_numbers_plus_png);    // assets/numbers/plus.png
LV_IMG_DECLARE(ui_img_numbers_slash_png);    // assets/numbers/slash.png
LV_IMG_DECLARE(ui_img_wallpaper_beach_png);    // assets/wallpaper/beach.png
LV_IMG_DECLARE(ui_img_wallpaper_christmas1_png);    // assets/wallpaper/christmas1.png
LV_IMG_DECLARE(ui_img_wallpaper_christmas2_png);    // assets/wallpaper/christmas2.png
LV_IMG_DECLARE(ui_img_wallpaper_future_png);    // assets/wallpaper/future.png
LV_IMG_DECLARE(ui_img_wallpaper_nature_png);    // assets/wallpaper/nature.png
LV_IMG_DECLARE(ui_img_wallpaper_thailand_png);    // assets/wallpaper/thailand.png
LV_IMG_DECLARE(ui_img_weather_clearnight_png);    // assets/weather/clearnight.png
LV_IMG_DECLARE(ui_img_weather_cloudy_png);    // assets/weather/cloudy.png
LV_IMG_DECLARE(ui_img_weather_cloudynight_png);    // assets/weather/cloudynight.png
LV_IMG_DECLARE(ui_img_weather_home_fall_png);    // assets/weather/home_fall.png
LV_IMG_DECLARE(ui_img_weather_home_rain_png);    // assets/weather/home_rain.png
LV_IMG_DECLARE(ui_img_weather_home_snow_png);    // assets/weather/home_snow.png
LV_IMG_DECLARE(ui_img_weather_partlycloud_png);    // assets/weather/partlycloud.png
LV_IMG_DECLARE(ui_img_weather_rain_png);    // assets/weather/rain.png
LV_IMG_DECLARE(ui_img_weather_snow_png);    // assets/weather/snow.png
LV_IMG_DECLARE(ui_img_weather_sunny_png);    // assets/weather/sunny.png
LV_IMG_DECLARE(ui_img_weather_thunderstorm_png);    // assets/weather/thunderstorm.png
LV_IMG_DECLARE(ui_img_weather_windy_png);    // assets/weather/windy.png

// FONTS
LV_FONT_DECLARE(ui_font_NixieOne48);
LV_FONT_DECLARE(ui_font_NotoSanThai16);
LV_FONT_DECLARE(ui_font_NotoSanThai20);

// UI INIT
void ui_init(void);
void ui_destroy(void);

void exit_clock_breathing(void);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
