// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: tune_bar

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void appStart(lv_event_t * e);
void resetScreenOffTimer(lv_event_t * e);
void livestreamMode(lv_event_t * e);
void musicPlayerMode(lv_event_t * e);
void chatBotMode(lv_event_t * e);
void informationMode(lv_event_t * e);
void utilityMode(lv_event_t * e);
void saveWiFiCredential(lv_event_t * e);
void scanNetwork(lv_event_t * e);
void toggleWiFi(lv_event_t * e);
void setBrightness(lv_event_t * e);
void setTimer(lv_event_t * e);
void setWallpaper(lv_event_t * e);
void loadStationFromSDCARD(lv_event_t * e);
void loadMusicFromSDCARD(lv_event_t * e);
void set_query_para_autoip(lv_event_t * e);
void setOffsetHour(lv_event_t * e);
void setOffsetMinute(lv_event_t * e);
void setTempUnit(lv_event_t * e);
void saveConfig(lv_event_t * e);
void readKeyboard(lv_event_t * e);
void readNumpad(lv_event_t * e);
void turnonScreen(lv_event_t * e);
void stopWeatherAnimation(lv_event_t * e);
void changeInfoPanelNext(lv_event_t * e);
void changeInfoPanelPrev(lv_event_t * e);
void showArrow(lv_event_t * e);
void updateAQIwidget(lv_event_t * e);
void volumeup(lv_event_t * e);
void volumemute(lv_event_t * e);
void volumedown(lv_event_t * e);
void playseek(lv_event_t * e);
void SeekingNow(lv_event_t * e);
void togglePlayingMode(lv_event_t * e);
void previoustrack(lv_event_t * e);
void fastReverse5(lv_event_t * e);
void playpause(lv_event_t * e);
void fastForward5(lv_event_t * e);
void nexttrack(lv_event_t * e);
void torch_ON(lv_event_t * e);
void showSystemInfo(lv_event_t * e);
void torch_OFF(lv_event_t * e);
void ota_update(lv_event_t * e);
void toggleMusicMode(lv_event_t * e);
void openLanUrlPanel(lv_event_t * e);
void saveLanUrlAndClose(lv_event_t * e);
void togglePlayerSource(lv_event_t * e);
void on_radio_language_changed(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
